# Introduction to Python and Natural Language Technologies

__Lecture 04, NumPy__

__March 2, 2020__

# Numpy

"NumPy is the fundamental package for scientific computing with Python."

https://numpy.org/

NumPy provides:

* linear algebra, Fourier transform and random numbers,
* easy-to-use matrices, arrays, tensors,
* heavy optimization and
* C/C++/Fortran integration.

"Numpy is the MATLAB of python!"

We import NumPy as `np` by convention:

In [1]:
import numpy as np

NumPy uses an underlying [BLAS](http://www.netlib.org/blas/) library, just as MATLAB does. These libraries employ vectorization.
* Anaconda uses IntelMKL (Intel's proprietary math library)
* If you install numpy manually, and you have previously installed [OpenBLAS](http://www.openblas.net/) (free, opensource), then NumPy will use that.

In [2]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/judit/miniconda3/envs/py38/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/judit/miniconda3/envs/py38/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/judit/miniconda3/envs/py38/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/judit/miniconda3/envs/py38/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/judit/miniconda3/envs/py38/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/judit/miniconda3/envs/py38/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/judit/miniconda3/envs/py38/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/judit/miniconda3/envs/py38/include']


# N-dimensional arrays

The core object of NumPy is `ndarray` (_$n$-dimensional array_).

In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(type(A))
A

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4],
       [5, 6]])

## Constructing arrays

Ndarray should never be constructed directly. A number of functions exist for constructing arrays:

__`np.array`__: manually specify each element

In [4]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

It can also take a sequence or a generator:

In [5]:
np.array(range(1, 7))

array([1, 2, 3, 4, 5, 6])

__`np.arange`__: range. Unlike the built-in `range`, `np.arange` supports float arguments

In [6]:
# range(1.1, 10.1, 1.5)
np.arange(1.1, 10.1, 1.5)

array([1.1, 2.6, 4.1, 5.6, 7.1, 8.6])

__`np.linspace`__: equally divided interval

In [7]:
A = np.linspace(0, 10, 5)
print(A.shape, type(A))
A

(5,) <class 'numpy.ndarray'>


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

This is often useful for creating a fine-grained scale:

In [8]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

__`np.ones`__: fills an array with 1s

In [9]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

__`np.zeros`__: fills an array with 0s

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

__`np.ones_like`__ and __`np.zeros_like`__ copy another array's shape and dtype:

In [11]:
A = np.array([[2, 3, -1], [1, 2, 6]])
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
A = np.array([[2.1, 3, -1], [1, 2, 6]])
np.zeros_like(A)

array([[0., 0., 0.],
       [0., 0., 0.]])

__`np.eye`__: creates an identity matrix, only works in 2D

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(4, dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

It doesn't have to be a square matrix:

In [15]:
np.eye(5, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

there is no `np.eye_like`, but you can use the following:

In [16]:
A = np.array([[2, 3, -1], [1, 2, 6]])
np.eye(*A.shape, dtype=A.dtype)

array([[1, 0, 0],
       [0, 1, 0]])

## Basic properties of ndarrays

`A.shape` is a tuple of the array's dimensions

In [17]:
A.shape

(2, 3)

and `dtype` is the type of the elements

In [18]:
A.dtype

dtype('int64')

In [19]:
A = np.array([1.5, 2])
A.shape, A.dtype

((2,), dtype('float64'))

In [20]:
A

array([1.5, 2. ])

`nbytes` gives us the memory footprint of the array:

In [21]:
A.nbytes

16

In [22]:
A = np.zeros((1000, ))
A.nbytes, A.dtype

(8000, dtype('float64'))

In [23]:
A = np.zeros((1000, ), dtype=np.bool)
A.nbytes

1000

In [24]:
A = np.zeros((1000, ), dtype=np.uint16)
A.nbytes

2000

## Accessing elements

Arrays are zero-indexed.

Accessing one row:

In [25]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.shape)
A[0], A[1], type(A[0])

(3, 2)


(array([1, 2]), array([3, 4]), numpy.ndarray)

Accessing one column:

In [26]:
A[:, 0], type(A[:, 0])

(array([1, 3, 5]), numpy.ndarray)

Accessing a single element:

In [27]:
A[2, 1], type(A[2, 1])

(6, numpy.int64)

Accessing a range of rows / columns

In [28]:
A[:2]  # or A[:2, :]

array([[1, 2],
       [3, 4]])

In [29]:
A[:, 1:]

array([[2],
       [4],
       [6]])

In [30]:
A[::2]

array([[1, 2],
       [5, 6]])

In general, an $n$-dimensional array requires $n$ indices to access its scalar elements.

In [31]:
B = np.array([[[1, 2, 3],[4, 5, 6]]])
B.shape, B.ndim

((1, 2, 3), 3)

In [32]:
B[0].shape

(2, 3)

In [33]:
B[0, 1], B[0, 1].shape

(array([4, 5, 6]), (3,))

3 indices access scalar members if ndim is 3

In [34]:
B[0, 1, 2], B[0, 1, 2].shape, type(B[0, 1, 2])

(6, (), numpy.int64)

## Slicing, advanced indexing

`:` retrieves the full size along that dimension.

In [35]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A[0])
print(A[0, :]) # first row
print(A[:, 0])  # first column

[[1 2 3]
 [4 5 6]]
[1 2 3]
[1 2 3]
[1 4]


These are 1D vectors, neither $1\times n$ nor $n\times1$ matrices!

In [36]:
A[0, :].shape, A[:, 0].shape

((3,), (2,))

In [37]:
B = np.array([[[1, 2, 3],[4, 5, 6]]])
B.shape

(1, 2, 3)

In [38]:
print(B[:, 1, :].shape)
B[:, 1, :]

(1, 3)


array([[4, 5, 6]])

In [39]:
B[0, 1, :], B[0, 1, :].shape

(array([4, 5, 6]), (3,))

In [40]:
type(B[0, 1, 1]), B[0, 1, 1]

(numpy.int64, 5)

In [41]:
isinstance(B[0, 1, 1], np.integer), isinstance(2, np.integer), isinstance(2, (int, np.integer))

(True, False, True)

All python range indexing also work, like reverse:

In [42]:
print(A[:, ::-1])
print(A[::-1, :])
print(A[:, ::2])

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[1 3]
 [4 6]]


## Advanced indexing

Advanced indexing is when the index is a list.

In [43]:
B = np.array([[[1, 2, 3], [4, 5, 6]]])
print(f"{B.shape = }")
print(f"{B[0, 0, [0, 2]].shape = }")
B[0, 0, [0, 2]]

B.shape = (1, 2, 3)
B[0, 0, [0, 2]].shape = (2,)


array([1, 3])

This selects the first and third "column":

In [44]:
B[0, :, [0, 2]]

array([[1, 4],
       [3, 6]])

or third and first "column":

In [45]:
B[0, :, [2, 0]]

array([[3, 6],
       [1, 4]])

one column can be selected multiple times and the list of indices doesn't have to be ordered

In [46]:
B[0, :, [2, 0, 2, 2]]

array([[3, 6],
       [1, 4],
       [3, 6],
       [3, 6]])

In [47]:
print(f"{B[0, 0, [0, 2, 0]].shape = }")
print(f"{B[0, 0, [0, 2, 0, 0]].shape = }")
print(f"{B[0, 0, [1]].shape = }")

B[0, 0, [0, 2, 0]].shape = (3,)
B[0, 0, [0, 2, 0, 0]].shape = (4,)
B[0, 0, [1]].shape = (1,)


### Advanced indexing theory

If all indices are lists:

<div align=center>B[$i_1$, $i_2$, $\ldots$].shape = (len($i_1$), len($i_2$), $\ldots$)</div>

The size of a particular dimension remains when the corresponding index is a colon (`:`).

If an index is a scalar then that dimension _disappears_ from the shape of the output.

If an index is a list then the dimension remains and its size is the length of the list.

One-length lists can be used as well. The resulting dimension remains but its size becomes one.

In [48]:
B = np.array([[[1, 2, 3], [4, 5, 6]]])
B[:, :, 2].shape

(1, 2)

In [49]:
B[:, :, 2]

array([[3, 6]])

In [50]:
B[:, :, [2]].shape

(1, 2, 1)

In [51]:
C = np.array([[1, 2, 3], [4, 5, 6]])
C

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
print(f"{C.shape = }")
print(f"{C[[0, 1, 0, 0, 0], [1, 2, 0, -1, 1]].shape = }")
C[[0, 1, 0, 0, 0], [1, 2, 0, -1, 1]]

C.shape = (2, 3)
C[[0, 1, 0, 0, 0], [1, 2, 0, -1, 1]].shape = (5,)


array([2, 6, 1, 3, 2])

## Under the hood

The default array representation is C style ([row-major](https://en.wikipedia.org/wiki/Row-_and_column-major_order)) indexing. But you shouldn't rely on the representation, it is not recommended to use the low level C arrays.

In [53]:
print(B.strides)
print(B.flags)

(48, 24, 8)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



# Operations on arrays

## Element-wise arithmetic operators

Arithmetic operators are overloaded, they act element-wise.

In [54]:
A = np.array([[1, 1], [2, 2]])
P = A >= 2
print(P)
print(P.dtype)

[[False False]
 [ True  True]]
bool


In [55]:
A + A

array([[2, 2],
       [4, 4]])

In [56]:
A * A

array([[1, 1],
       [4, 4]])

In [57]:
np.exp(A)

array([[2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 ]])

In [58]:
np.log10(A)

array([[0.     , 0.     ],
       [0.30103, 0.30103]])

In [59]:
2 ** A

array([[2, 2],
       [4, 4]])

In [60]:
A ** 2

array([[1, 1],
       [4, 4]])

In [61]:
1 / A

array([[1. , 1. ],
       [0.5, 0.5]])

## Matrix algebraic operations

`dot` is the standard matrix product

In [62]:
A = np.array([[1, 2], [3, 4]])
A.dot(A)

array([[ 7, 10],
       [15, 22]])

inner dimensions must match

In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3], [4, 5, 6]])
print(f"{A.shape = }, {B.shape = }")
A.dot(B)
# B.dot(A)  # raises ValueError

A.shape = (2, 2), B.shape = (2, 3)


array([[ 9, 12, 15],
       [19, 26, 33]])

Inverse can be computed by `np.linalg.inv`:

In [64]:
A_inv = np.linalg.inv(A)
print(A_inv)

A_inv.dot(A)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [65]:
np.allclose(A_inv.dot(A), np.eye(2), 1e-10)

True

In [66]:
np.round(A_inv.dot(A), 5)

array([[1., 0.],
       [0., 1.]])

pseudo-inverse can be computed with `np.linalg.pinv`

In [67]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A_pinv = np.linalg.pinv(A)

A.dot(A_pinv).dot(A)

array([[1., 2., 3.],
       [4., 5., 6.]])

There is a `matrix` class as well, for which `*` acts as a matrix product.

In [68]:
M = np.matrix([[1, 2], [3, 4]])
print(np.multiply(M, M))
print(M * M)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## Transpose

__`transpose`__ rearranges the dimensions of an array:

In [69]:
A = np.array([[[1, 2, 3], [4, 5, 6]]])
print(f"{A.shape = }")
print(f"{A.transpose(1, 0, 2).shape = }")

A.shape = (1, 2, 3)
A.transpose(1, 0, 2).shape = (2, 1, 3)


The parameters of transpose are the axes in their new order. All axes must be listed exactly once:

In [70]:
# print(f"{A.transpose(1, 0).shape = }")
# print(f"{A.transpose(1, 0, 0).shape = }")
# print(f"{A.transpose(1, 0, 2, 1).shape = }")

__T__ is a shorthand for __`.transpose(1, 0)`__, it transposes the first two dimensions

In [71]:
np.array([[1, 2, 3], [4, 5, 6]]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
A.transpose(1, 0)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Casting and types

C types are available in `numpy`

In [74]:
P = np.array([[1.2, 1], [-1.5, 0]])
print(P.dtype)
P.astype(int)

float64


array([[ 1,  1],
       [-1,  0]])

In [75]:
P = np.array([[1.2, 1], [-1.5, 0]])
(-P.astype(int)).astype(np.uint32)

array([[4294967295, 4294967295],
       [         1,          0]], dtype=uint32)

In [76]:
np.array([[1, 2], [3, 4]], dtype=np.float32)

array([[1., 2.],
       [3., 4.]], dtype=float32)

Directly converts strings to numbers

In [77]:
np.float32('-10')

-10.0

`dtype` can be specified during array creation

In [78]:
np.array(['10', '20'], dtype=np.float16)
# np.array(['10ab', '20'], dtype=np.float16)  # raises ValueError

array([10., 20.], dtype=float16)

__`np.datetime64`__ for dates:

In [79]:
np.datetime64("2018-03-10")

numpy.datetime64('2018-03-10')

It supports basic time arithmetics:

In [80]:
np.datetime64("2018-03-10") - np.datetime64("2017-12-13")

numpy.timedelta64(87,'D')

String arrays:

In [81]:
T = np.array(['apple', 'plum'])
print(T)
print(T.shape, T.dtype, type(T))

['apple' 'plum']
(2,) <U5 <class 'numpy.ndarray'>


Fixed length character arrays, longer string are truncated:

In [82]:
T = np.array(['apple', 'plum'])
T[0] = "banana"
T

array(['banan', 'plum'], dtype='<U5')

## Changing shape

The shape of an array can be modified with `reshape`, as long as the number of elements remains the same. The underlying elements are unchanged and not copied in the memory.

In [83]:
B = np.array([[[1, 2, 3], [4, 5, 6]]])
print(B.shape)
B.reshape((2, 3))

(1, 2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
B.reshape((3, 2)).shape, B.shape

((3, 2), (1, 2, 3))

A `ValueError` is raised if the shape is invalid:

In [85]:
# B.reshape(7)  # raises ValueError

We have a shorthand now to create arrays like B:

In [86]:
np.arange(1, 7).reshape((1, 2, 3))

array([[[1, 2, 3],
        [4, 5, 6]]])

Size `-1` can be used to span the resulted array as much as it can in that dimension.

In [87]:
X = np.arange(12).reshape((2, -1, 2))
print(f"{X.shape = }")
print(X)

X.shape = (2, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


But only one dimension can have -1 as its size:

In [88]:
# X = np.arange(12).reshape((2, -1, 2, -1))  # raises ValueError

In [89]:
X = np.arange(12).reshape((2, 3, 2))

__`resize`__ deletes elements or fills with zeros but it works only _inplace_.

In [90]:
X = np.array([[1, 2], [3, 4]])
# X.resize((5, 3))
X.resize((2, 1))
X

array([[1],
       [2]])

However, `np.resize` (not a member) works differently

In [91]:
X = np.array([[1, 2], [3, 4]])
np.resize(X, (5, 3))

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4],
       [1, 2, 3]])

`X` is unchanged:

In [92]:
X

array([[1, 2],
       [3, 4]])

In [93]:
np.arange(12).reshape((2, 3, 2)).sum()

66

## Concatenation

Arrays can be concatenated along any axis as long as their shapes are compatible.

In [94]:
A = np.arange(6).reshape(2, -1)
B = np.arange(10, 18).reshape(2, -1)
print(f"{A.shape = }")
print(f"{B.shape = }")

np.concatenate((A, B), axis=1)

A.shape = (2, 3)
B.shape = (2, 4)


array([[ 0,  1,  2, 10, 11, 12, 13],
       [ 3,  4,  5, 14, 15, 16, 17]])

In [95]:
np.concatenate((A, B), axis=-1)  # last dimension

array([[ 0,  1,  2, 10, 11, 12, 13],
       [ 3,  4,  5, 14, 15, 16, 17]])

In [96]:
# np.concatenate((A, B))  # ValueError, axis=0 is the default

In [97]:
np.concatenate([A, B, A, B], axis=1)

array([[ 0,  1,  2, 10, 11, 12, 13,  0,  1,  2, 10, 11, 12, 13],
       [ 3,  4,  5, 14, 15, 16, 17,  3,  4,  5, 14, 15, 16, 17]])

Concatenating on the first and second dimension of 2D arrays is a very common operation, there are shorthands:

In [98]:
A = np.arange(6).reshape(2, -1)
B = np.arange(8).reshape(2, -1)
A, B

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [99]:
np.hstack((A, B))

array([[0, 1, 2, 0, 1, 2, 3],
       [3, 4, 5, 4, 5, 6, 7]])

In [100]:
# np.vstack((A, B))  # raises ValueError

In [101]:
A = np.arange(6).reshape(-1, 2)
B = np.arange(8).reshape(-1, 2)
print(A.shape, B.shape)

# np.hstack((A, B))
np.vstack((A, B))

(3, 2) (4, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

`np.stack` puts the arrays next to each other along a **new** dimension

In [102]:
A.shape, np.stack((A, A, A, A, A, A)).shape

((3, 2), (6, 3, 2))

In [103]:
np.stack((A, A, A, A)).shape

(4, 3, 2)

Block matrix

In [104]:
np.concatenate([np.concatenate([np.ones((2,2)), np.zeros((2,2))], axis=1),
                np.concatenate([np.zeros((2,2)), np.ones((2,2))], axis=1)], axis=0)

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

## Iteration

Arrays support iteration but it is rarely used. Vectorized operations are much more efficient.

By default, iteration takes place in the first (outermost) dimension.

In [105]:
A = np.arange(6).reshape(2, -1)
for row in A:
    print("Row:", row)

Row: [0 1 2]
Row: [3 4 5]


But you can slice the desired elements for a loop.

In [106]:
B = np.arange(6).reshape(1, 2, 3)

for x in B[0, 0, :]:
    print(x)

0
1
2


We can flatten the matrix and iterate through the elements using `flat`:

In [107]:
for a in B.flat:
    print(a)

0
1
2
3
4
5


In [108]:
for k in range(B.shape[2]):
    print(B[:, :, k])

[[0 3]]
[[1 4]]
[[2 5]]


# Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

For example a $1\times 1$ array can be multiplied with matrices, just like a scalars times a matrix.

In [109]:
A = np.arange(6).reshape(2, -1)
s = 2.0 * np.ones((1, 1))
print(s)
print(A)
print(f"{A.shape = }, {s.shape =}")
s * A

[[2.]]
[[0 1 2]
 [3 4 5]]
A.shape = (2, 3), s.shape =(1, 1)


array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

A one-length vector can be multiplied with a matrix:

In [110]:
print(np.ones((1,)) * A)
np.ones(()) * B

[[0. 1. 2.]
 [3. 4. 5.]]


array([[[0., 1., 2.],
        [3., 4., 5.]]])

However you cannot perform element-wise operations on uneven sized dimensions:

In [152]:
# np.ones((2, 3)) + np.ones((3, 2))  # raises ValueError

This behavior is defined via _broadcasting_. If an array array has a dimension of length one, then it can be _broadcasted_, which means that it can span as much as the operation requires (operation other than indexing).

In [153]:
np.arange(3).reshape((1, 3)) + np.zeros((20, 3))

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [154]:
np.arange(3).reshape((3, 1)) + np.zeros((3, 14))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [155]:
np.arange(3).reshape((3, 1)) + np.zeros((6, 14))

ValueError: operands could not be broadcast together with shapes (3,1) (6,14) 

More than one dimension can be broadcasted at a time.

In [ ]:
np.arange(3).reshape((1, 3, 1)) + np.zeros((2, 3, 6))

In [156]:
(np.arange(3).reshape((1, 3, 1)) + np.zeros((2, 3, 6))).shape

(2, 3, 6)

In [157]:
np.arange(15).reshape((1, 3, 5)) + np.zeros((2, 3, 1))

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]]])

## Theory

If an array has the shape `(1, 3, 1)`, its first and third dimensions can be broadcast.

The index triple `[x, y, z]` accesses its elements as `[0, y, 0]` even if $x>0$ and $z>0$. In other words, broadcast dimensions are repeated as many times as the operation needs it.

Non-existent dimensions can be broadcast.

In terms of shapes: `(k,) + (i, j, k)` means that a vector plus a three dimensional array (of size $i \times j \times k$). The index `[i, j, k]` of the broadcast vector degrades to `[k]`.

Denoting false dimensions with `None`, we can illustrate broadcasting:

`(2,) + (3, 2, 2)` results the broadcast `(None, None, 2) + (3, 2, 2)`.

False dimensions are __always__ prepended at the front, or in the place of 1-length dimensions.

False dimensions can be forced with the `None` index.
These exist only for broadcasting.

`(2,) + (3, 2, 2) -> (None, None, 2) + (3, 2, 2) = (3, 2, 2)`

is OK, but

`(3,) + (3, 2, 2) -> (None, None, 3) + (3, 2, 2)`

is NOT.

In [158]:
def test_broadcast(x, y):
    try:
        A = np.ones(x) + np.ones(y)
        print("Broadcastible")
    except ValueError:
        print("Not broadcastible")

        
test_broadcast((3,), (3, 2, 2))
test_broadcast((2,), (3, 2, 2))
test_broadcast((3, 1, 4), (3, 2, 1))
test_broadcast((3, 1, 4), (3, 2, 2))
test_broadcast((1, 4), (3, 2, 4))

Not broadcastible
Broadcastible
Broadcastible
Not broadcastible
Broadcastible


We can force broadcasting by using `None` in place of the broadcastible dimension.

In [159]:
(np.ones(3)[:, None, None] + np.ones((3, 2, 2))).shape

(3, 2, 2)

The result in shapes: `(3, None, None) + (3, 2, 2) = (3, 2, 2)`

## Example

This one liner to produce a complex "grid".

In [160]:
np.arange(5)[:, None] + 1j * np.arange(5)[None, :]

array([[0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j],
       [1.+0.j, 1.+1.j, 1.+2.j, 1.+3.j, 1.+4.j],
       [2.+0.j, 2.+1.j, 2.+2.j, 2.+3.j, 2.+4.j],
       [3.+0.j, 3.+1.j, 3.+2.j, 3.+3.j, 3.+4.j],
       [4.+0.j, 4.+1.j, 4.+2.j, 4.+3.j, 4.+4.j]])

Due to the default behavior, a vector behaves as a row vector and acts row-wise on a matrix.

`(n,) -> (None, n)`

In [161]:
np.arange(5) + np.zeros((5, 5))

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

We can explicitly reshape it:

In [162]:
np.arange(5).reshape(-1, 1) + np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

This behavior does not apply to non-element-wise operations, like `dot` product.

# Reductions

Sum over an axis:

In [163]:
Y = np.arange(24).reshape(2, 3, 4)
Y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [164]:
Y.sum()  # sum every element

276

In [165]:
Y.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [166]:
Y.sum(axis=0).shape

(3, 4)

In [167]:
Y.sum(axis=(1, 2)) #.shape

array([ 66, 210])

In [168]:
i = 0
ysum = [0, 0]

for j in range(Y.shape[1]):
    for k in range(Y.shape[2]):
        ysum[0] += Y[0, j, k]
        ysum[1] += Y[1, j, k]
ysum

[66, 210]

In [169]:
Y.sum(axis=-1)

array([[ 6, 22, 38],
       [54, 70, 86]])

`mean, std, var` work similarly but compute the mean, standard deviation and variance along an axis or the full array:

In [170]:
Y.mean()

11.5

In [171]:
Y.mean(axis=(2, 0))

array([ 7.5, 11.5, 15.5])

In [172]:
Y = np.arange(24).reshape(2, 3, 4)
Y.mean(axis=(2)).shape

(2, 3)

In [173]:
Y.std()

6.922186552431729

In [174]:
Y.max(axis=1)

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

# `np.random`

Numpy has a rich random subpackage.

In [175]:
np.random.random()

0.05630327568183735

`np.random.rand`  or `np.random.random` samples random `float64` numbers from $[0, 1)$ with uniform sampling.

In [176]:
np.random.random(size=(2, 3))

array([[0.11881792, 0.11752625, 0.6492103 ],
       [0.74604488, 0.58336877, 0.96217255]])

How can we generate random numbers between 20 and 30?

In [177]:
# TODO
10 * np.random.random(size=(2, 3)) + 20

array([[23.7487058 , 22.85712086, 28.68599128],
       [22.23595839, 29.63222539, 20.12154475]])

Other distributions:

In [178]:
np.random.uniform(1, 2, (2, 2))

array([[1.96987883, 1.04315991],
       [1.89114311, 1.52770111]])

In [179]:
np.random.standard_normal(size=(3, 2))  # np.random.normal(0, 1, size=(3, 2))

array([[ 0.47362739,  0.05435058],
       [ 2.2757613 ,  0.40622669],
       [-0.4319422 ,  1.85996701]])

In [180]:
np.random.normal(10, 100, size=(3, 2))

array([[ 130.04115484,  191.60877902],
       [  -1.09319356,  107.63091265],
       [-135.28494591,   88.40064109]])

Discrete randoms:

In [181]:
np.random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"], 10, replace=True)

array(['Q', '4', '10', '8', '10', 'Q', '2', 'Q', 'Q', '5'], dtype='<U2')

`choice` accepts custom probabilities:

In [182]:
np.random.choice(list('abcdef'), 10, p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.5])

array(['f', 'f', 'f', 'f', 'd', 'f', 'f', 'b', 'f', 'f'], dtype='<U1')

In [183]:
print(np.random.permutation(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]))

['7' 'J' '4' 'A' 'Q' '8' '6' '10' 'K' '9' '5' '3' '2']


`permutation` permutes the first (outermost) dimension.

In [184]:
print(np.random.permutation(np.arange(9).reshape((3, 3))))

[[6 7 8]
 [3 4 5]
 [0 1 2]]


# Miscellaneous

## Shuffling

In place

In [185]:
A = np.arange(10)
np.random.shuffle(A)
A

array([4, 3, 8, 5, 2, 9, 6, 7, 1, 0])

Fixing the seed:

In [186]:
np.random.seed(42)
A = np.arange(10)
np.random.shuffle(A)
A

array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6])

## Split dataset into train, dev and test

In [187]:
dataset = set() 
letters = list("abcdef")
while len(dataset) < 100:
    word_len = np.random.randint(3, 7)
    word = "".join(np.random.choice(letters, size=word_len))
    dataset.add(word)
dataset = np.array(list(dataset))

In [188]:
dataset

array(['aedec', 'bbfed', 'dbb', 'aad', 'adeda', 'ebebad', 'aeed',
       'ecdfcc', 'ecede', 'deaeea', 'cfadaf', 'caad', 'edfc', 'cdaa',
       'eefecd', 'daabac', 'eddded', 'cefa', 'ebbad', 'dfe', 'fedbf',
       'cfa', 'fae', 'debdb', 'eadad', 'ebbc', 'aaac', 'ccfdbb', 'fecdd',
       'fed', 'ecfc', 'fcdea', 'cad', 'bfdcca', 'caaddf', 'adfdf', 'baf',
       'fbcf', 'aebfc', 'adbaf', 'bdfe', 'cce', 'dcbcc', 'bdbfff',
       'ffdcdb', 'aeea', 'daeea', 'cdfad', 'badcdd', 'cbd', 'fcafe',
       'ffdafe', 'faaac', 'adea', 'ffff', 'bebe', 'bfedaa', 'bbd',
       'ffcbda', 'afffd', 'befad', 'adbf', 'ebdf', 'acecea', 'dddd',
       'bdadf', 'ccedc', 'fef', 'aacfbe', 'fbbf', 'aca', 'fde', 'ccacca',
       'eeacba', 'cef', 'dbbf', 'dbbc', 'caabcd', 'eecaac', 'ecda',
       'ecbc', 'caadcc', 'babe', 'bfbcbb', 'cbddf', 'dfeb', 'bdea', 'bdd',
       'bcae', 'cacd', 'aedb', 'babf', 'aabfbc', 'facae', 'dbadd', 'fcdd',
       'fefbb', 'edaffe', 'fcab', 'edf'], dtype='<U6')

In [189]:
all_idx = np.arange(len(dataset))
np.random.shuffle(all_idx)
all_idx

array([19, 21, 76, 43,  3,  0, 32, 50,  2, 91, 44, 42, 59, 68, 93,  1, 26,
       94, 96, 65, 37, 55,  5, 95, 71, 82, 56, 45, 14, 17, 31, 10, 99, 41,
       49, 47, 52, 53, 39, 38, 62, 69, 66, 84, 24, 88, 34,  4, 15, 46, 64,
       51, 30, 13, 27, 90,  8, 60, 79, 40, 81, 77, 78, 18, 58, 70, 87, 16,
       29, 75, 12, 54, 11, 36, 61, 22, 98, 83, 48, 63, 23, 72,  9, 85, 20,
       35, 28, 74, 57, 67,  6, 33, 97, 73, 25, 92,  7, 89, 80, 86])

In [190]:
train_idx = all_idx[:80]
dev_idx = all_idx[80:90]
test_idx = all_idx[90:]

train_dataset = dataset[train_idx]
dev_dataset = dataset[dev_idx]
test_dataset = dataset[test_idx]

In [191]:
dev_dataset

array(['debdb', 'ccacca', 'deaeea', 'dfeb', 'fedbf', 'adfdf', 'fecdd',
       'cef', 'bbd', 'fef'], dtype='<U6')

## Boolean indexing and `np.where`

Selecting elements that satisfy a certain condition:

In [192]:
A = np.random.random((4, 3))
print(A.mean())
A

0.4957586653895755


array([[0.98600106, 0.75337819, 0.37625959],
       [0.08350072, 0.77714692, 0.55840425],
       [0.42422201, 0.90635439, 0.11119748],
       [0.4926251 , 0.01135364, 0.46866064]])

Selecting elements greater than the mean of the matrix:

In [193]:
A > A.mean()

array([[ True,  True, False],
       [False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [194]:
A[A > A.mean()]

array([0.98600106, 0.75337819, 0.77714692, 0.55840425, 0.90635439])

`np.where` returns the advanced indices for which the condition is satisfied (where the boolean array is `True`):

In [195]:
np.where(A > A.mean())

(array([0, 0, 1, 1, 2]), array([0, 1, 1, 2, 1]))

In [196]:
A[np.where(A > A.mean())]

array([0.98600106, 0.75337819, 0.77714692, 0.55840425, 0.90635439])

actually `np.where` returns the indices of elements that evaluate to nonzero

In [197]:
np.where([2, -1, 0, 5])

(array([0, 1, 3]),)

## `np.tile`, `np.repeat`

In [198]:
np.tile([1, 2, 3], reps=(4, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [199]:
np.repeat([1, 2, 3], repeats=4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])